#!/bin/bash

# ------------------------------------------------------------------------------
# | NPM Settings                                                               |
# ------------------------------------------------------------------------------

run_npm() {

    # Check for npm
    if type_exists "npm"; then

        # Install packages globally and quietly
        e_header "Installing Node packages"

        npm install -g grunt-cli gulp bower imageoptim-cli browserify uglifyjs jshint eslint stylus browser-sync markdown jade mocha coveralls istanbul babel react-tools webpack clean-css node-sass express karma yo ionic cordova typescript lodash phantomjs casperjs

        e_success "Node packages successfully installed!"

    else

        printf "\n"
        e_error "Error: npm not found."
        printf "Aborting...\n"
        exit

    fi

}